### PR TITLE
Fix OTP/passkey login flow handling

### LINKED ISSUE #449: instead of getting OAuth code, script redirects to passkey creation
Image

Image

---

[1/14/2026, 2:10:46 PM] [`censored`] [ERROR] MOBILE [FLOW] Mobile flow failed for `censored`: Request failed with status code 401

### PR DESCRIPTION
**Pull request by Titaniumtown**
Some issues cropped up with the login flow resulting from [3.1.0](https://github.com/TheNetsky/Microsoft-Rewards-Script/commit/576899f39d662a8501a0c751310a0fdee49fc316).

Specifically I was hitting failures with the passkey creation, which fails. I don't know why this stuff was being activated in the first place, but I added code that will just skip it.

I also was hitting issues with the bot getting lost on the login flow and ending up on the OTP page. I am not 100% about this code though.

Closes: #449 & #429

### CODE REVIEW

File: src/browser/auth/Login.ts [hunk 1]
```diff
@@ -56,6 +57,10 @@ export class Login {
         totpInputOld: 'form[name="OneTimeCodeViewForm"]',
         identityBanner: '[data-testid="identityBanner"]',
         viewFooter: '[data-testid="viewFooter"] >> [role="button"]',
+        otherWaysToSignIn:
+            'span[role="button"]:has-text("Other ways to sign in"), span[role="button"]:has-text("other ways")',
```
Comment (TheNetsky) [inline src/browser/auth/Login.ts]: I'm not sure if having a text based selector is the way to go. I've been purposely trying to avoid this due to this not working once the language is not set to English.

**Comment by meichengg** [comment]
Hey there, thanks for helping me with this issue, i tested your PR in my case #429, i got loop forever. For my case, just need to click Use your password then paste the password, just like in the image.

image

And this is your PR result for my case below.

2026-01-15 at 17 23 34@2x

**Comment by Titaniumtown** [comment]
@meichengg Oh interesting, it didn't do this for me. I will investigate further. Did you wait and give it time to navigate that page?

**Comment by meichengg** [comment]
> @meichengg Oh interesting, it didn't do this for me. I will investigate further. Did you wait and give it time to navigate that page?

I just let the tool do its job, i didn't touch anything.

File: src/browser/auth/Login.ts (hunk 1 above)
Comment (Titaniumtown) [reply src/browser/auth/Login.ts]: Resolved. ty

**Comment by TheNetsky** [comment]
Can either @Titaniumtown implement the fixes from the PR from @meichengg or vice versa so one of the PR's can be closed.

**Comment by Titaniumtown** [comment]
I can cherry-pick the changes from @meichengg's PR.

**Comment by Titaniumtown** [comment]
@meichengg I included you on the commit I just pushed as a co-author.


The git histories got a bit confused so I just merged the commits together haha.

**Comment by Titaniumtown** [comment]
@TheNetsky Done :)

**Comment by meichengg** [comment]
Thank you, much appreciated. 🙏🏻
